### PR TITLE
disable assets creation for assets.ubuntu.com upgrade

### PR DESCRIPTION
**Pull request by goulinkh**
## Done

- A warning message that explains that assets creation is disabled
- Remove asset creation form

## QA
- Checkout this branch
- Run `dotrun`
- Go to http://0.0.0.0:8018/create
- Make sure that the creation form is removed and that there is a notification message

### Notification message
image

### CODE REVIEW

**Comment by anthonydillon** [comment]
Could this behaviour be toggled on an environment variable? Feel like it might be useful in the future.

**Comment by goulinkh** [comment]
> Could this behaviour be toggled on an environment variable? Feel like it might be useful in the future.

Sure! let me add that.

**Comment by goulinkh** [comment]
@anthonydillon As this project is moved to the new version of assets, we need to add it to the new version once it's deployed instead of adding the env variable to this repo.

**Review by anthonydillon — APPROVED** [review]
LGTM

**Comment by goulinkh** [comment]
@cristinadresch I created a [new issue](https://github.com/canonical-web-and-design/assets.ubuntu.com/issues/170) for this, we can work on it as soon as the deployment process is done, [doc with latest details](https://docs.google.com/document/d/1zKwvsRuBNIdGPYhWGAVJsmgmGBi25GyjEeR-MSDT-p4/edit#heading=h.u163d8v1go7r).

**Comment by goulinkh** [comment]
@davegoddard42 Joao is preparing the issues for deploying the new assets to the new cluster (PS5), and we will start working on this after Christmas

**Comment by sowasred2012** [comment]
@goulinkh do you know what the latest with this is? Are we still waiting on IS?

**Comment by goulinkh** [comment]
Hey @sowasred2012 The assets project is planned during the maintenance sprint.

**Pull request merged**
